// generated by CommonFindPackage.cmake, do not edit.

#ifndef Brion_DEFINES_Linux_H
#define Brion_DEFINES_Linux_H

#ifndef BRION_USE_BOOST
#  define BRION_USE_BOOST 1
#endif
#ifndef BRION_USE_BOOST
#  define BRION_USE_BOOST 1
#endif
#ifndef BRION_USE_HIGHFIVE
#  define BRION_USE_HIGHFIVE 1
#endif
#ifndef BRION_USE_KEYV
#  define BRION_USE_KEYV 1
#endif
#ifndef BRION_USE_LUNCHBOX
#  define BRION_USE_LUNCHBOX 1
#endif
#ifndef BRION_USE_MVDTOOL
#  define BRION_USE_MVDTOOL 1
#endif
#ifndef BRION_USE_OPENMP
#  define BRION_USE_OPENMP 1
#endif
#ifndef BRION_USE_PYTHONINTERP
#  define BRION_USE_PYTHONINTERP 1
#endif
#ifndef BRION_USE_PYTHONLIBS
#  define BRION_USE_PYTHONLIBS 1
#endif
#ifndef BRION_USE_SERVUS
#  define BRION_USE_SERVUS 1
#endif
#ifndef BRION_USE_SPHINX
#  define BRION_USE_SPHINX 1
#endif
#ifndef BRION_USE_VMMLIB
#  define BRION_USE_VMMLIB 1
#endif
#ifndef Linux
#  define Linux 1
#endif
#ifndef BRION_USE_CXX11
#  define BRION_USE_CXX11 1
#endif
#ifndef BRION_LITTLEENDIAN
#  define BRION_LITTLEENDIAN 1
#endif

#endif
