// generated by CommonLibrary.cmake, do not edit.

/**
 * @file include/brion/api.h
 * Defines export visibility macros for library Brion.
 */

#ifndef BRION_API_H
#define BRION_API_H

#if defined(_MSC_VER) || defined(__declspec)
#  define BRION_DLLEXPORT __declspec(dllexport)
#  define BRION_DLLIMPORT __declspec(dllimport)
#else // _MSC_VER
#  define BRION_DLLEXPORT
#  define BRION_DLLIMPORT
#endif // _MSC_VER

#if defined(BRION_STATIC)
#  define BRION_API
#elif defined(BRION_SHARED)
#  define BRION_API BRION_DLLEXPORT
#else
#  define BRION_API BRION_DLLIMPORT
#endif

#if defined(BRION_SHARED_INL)
#  define BRION_INL BRION_DLLEXPORT
#else
#  define BRION_INL BRION_DLLIMPORT
#endif

#endif
