/*
 * Copyright (C) 2015 Adrien Devresse <adrien.devresse@epfl.ch>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */
#include <iostream>
#include <exception>
#include <fstream>

#include <morpho/morpho_h5_v1.hpp>

using namespace std;

std::string version(){
    return std::string( MORPHO_VERSION_MAJOR "." MORPHO_VERSION_MINOR );
}

const std::string gmsh_header =
"/***************************************************************\n"
" * gmsh file generated by morpho-tool\n"
"****************************************************************/\n\n";


void export_morpho_to_mesh(const std::string & filename_morpho, const std::string & filename_geo){
    morpho::h5_v1::morpho_reader   reader(filename_morpho);

    auto points = reader.get_points();

    std::ofstream geo_stream(filename_geo);

    geo_stream << gmsh_header << "\n";

    geo_stream << "lcar1 = .1;\n"
               << "lcar2 = .0005;\n"
               << "lcar3 = .055;\n";

    assert(points.shape()[1] > 3);


    geo_stream << "// export morphology points \n";

    const std::size_t rows = points.shape()[0];

    std::size_t id_point =0;

    for(std::size_t i =0; i < rows; ++i){
        geo_stream << "Point("<< id_point << ") = "
                   << "{"<< points[i][0] << "," << points[i][1] << "," << points[i][2] << ",lcar2} ;\n";
        id_point++;
    }

    geo_stream << "\n\n";




}


int main(int argc, char** argv){

    try{
        export_morpho_to_mesh(argv[1], argv[2]);
    }catch(std::exception & e){
        std::cerr <<  argv[0] << " Error " << e.what() << std::endl;
        exit(-1);
    }
    return 0;
}

