name: Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


env:
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_BUILD_VERBOSITY: 2
  # Only build on Python 3.x
  CIBW_BUILD: 'cp3?-*'
  CIBW_SKIP: 'cp35-* cp39-* *-manylinux_i686'
  CIBW_BEFORE_TEST: pip install -r tests/requirement_tests.txt
  CIBW_TEST_COMMAND: nosetests {project}/tests
  MACOSX_DEPLOYMENT_TARGET: '10.13'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Build wheels on Linux
        if: runner.os == 'Linux'
        env:
          CIBW_BEFORE_BUILD: 'yum update -y; yum -y install hdf5-devel'
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build wheels Mac OS
        if: runner.os == 'macOS'
        env:
          CIBW_BEFORE_BUILD: 'brew install cmake hdf5'
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Store wheel as artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: wheelhouse

  upload_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    name: Upload wheels to PyPI
    steps:
      - name: Download artifacts produced during the build_wheels job
        uses: actions/download-artifact@v2
        with:
          name: wheelhouse
          path: wheelhouse

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: wheelhouse

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
